### ISSUE TITLE
Error SQLSTATE[] SQLDriverConnect: 0

### ISSUE THREAD

**Issue by rizaldywirawan** [zoilomora/laravel-msaccess#2]
Hola @zoilomora,

I use your package for my project, it's good because i can connect to the Access DB (finally >.<). But I don't know what happen, sometimes, when the user use the application, the Laravel error and show this message:

`SQLSTATE[] SQLDriverConnect: 0`

To fix this, i have to restart the Laragon (since I use it), but i guess there's something wrong, i don't know why. Maybe I do something wrong too, but i already check my code and nothing suspicious.

Do you know what happen?

Thank You.

**Comment by zoilomora** [comment]
Hello,

Sorry I did not answer you before. Notifications did not work for me and I've seen it now.

I do not have much time to test now, did you solve the problem?

**Comment by robjbrain** [comment]
I'm getting the same error:

> SQLSTATE[IM012] SQLDriverConnect: 0 [unixODBC][Driver Manager]DRIVER keyword syntax error

My config file looks like this:

```
'access' => [
            'driver' => 'pdo_access',
            'connection_string' => 'dsn=' . database_path('name_of_my_file.mdb'),
            'database' => '',
            'username' => '',
            'password' => '',
            'table_prefix' => '',
        ]
```

There don't seem to be any results on Google for the same error

**Comment by zoilomora** [comment]
Hello, the DSN is not the path of the file.

Try to do the following:
https://www.youtube.com/watch?v=_kUYPqauyyo

Set the correct DSN name :)

**Comment by robjbrain** [comment]
@zoilomora thanks I figured that DSN meant something else eventually, although i'm on vagrant/homestead runningUbuntu so i'm not sure the suggested method of creating a DSN name will help.

Is it possible to use this without a DSN name?

Such as:

```
Driver={Microsoft Access Driver (*.mdb)};Dbq=' . database_path('path_to_my_file.mdb');
```

Source for that example: http://php.net/manual/en/function.odbc-connect.php#16919

That example results in a different error, although i'm not surprised as I don't think that's how it's meant to work. I'll post the error anyway though:

> SQLSTATE[01000] SQLDriverConnect: 0 [unixODBC][Driver Manager]Can't open lib 'Microsoft Access Driver (*.mdb)' : file not found

I was hoping I could just have a .mdb file on my server and talk to it via Eloquent without having to be running on windows.

**Comment by zoilomora** [comment]
@robjbrain I have not tried the way you suggest.
I suppose it should work as long as you have installed the drivers.

The ODBC requires a driver for the Access databases.

**Comment by zoilomora** [comment]
I think this example is in Windows, I'm not sure.
http://php.net/manual/en/function.odbc-connect.php#16919

**Comment by robjbrain** [comment]
To anyone else finding this I made quite alot of progress using this guide: https://gist.github.com/amirkdv/9672857

You need to use both:

`sudo apt-get install mdbtools`

and

`sudo apt-get install odbc-mdbtools`

But eventually hit an error I couldn't figure out:

> SQLSTATE[IM004] SQLDriverConnect: 0 [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed

I hope that helps someone

**Comment by docktermj** [comment]
Related issue: https://github.com/microsoft/mssql-docker/issues/431
