### ISSUE TITLE
Set charset to utf-8

### ISSUE THREAD

**Issue by jaysoniscale** [zoilomora/laravel-msaccess#4]
Hi I'm having an error querying a table with columns names written in other language (french) 

> renaming of the column name is not an option so I tried to use the existing column names.

`DB::select("SELECT * FROM Agenda_CHOKOUHI WHERE NuméroPatient = ?", [3]);`

I tried adding the charset => utf-8 on the database config but to no avail.

`'access' => [
            'driver' => 'pdo_access',
            'connection_string' => 'FILEDSN=C:\Users\Adrian\Documents\Spelogic.dsn;Uid=admin;Pwd=;',
            'username' => env('DB_USERNAME', 'forge'),
            'password' => '',
            'table_prefix' => '',
            'charset' => 'utf8',
        ]`

**Comment by geek2200** [comment]
Hi, I have problem to showing utf8 char set. 
Adding utf-8 charset to database config but problem not solved.
```
'access' => [
			'driver' => 'pdo_access',
			'connection_string' => 'dsn=',
			'username' => '',
			'password' => '',
			'charset' => 'UTF-8',
			'table_prefix' => '',
		]
```

**Comment by zoilomora** [comment]
From what I understand.. In ODBC to MDB communication it _is not possible to specify charset_.

try this to transform the results:
```php
$field = mb_convert_encoding($field, 'UTF-8', 'Windows-1252');
```

and this for column names:
```php
$column = mb_convert_encoding('NuméroPatient', 'Windows-1252', 'UTF-8');
$sql = "SELECT * FROM Agenda_CHOKOUHI WHERE {$column} = ?";
DB::select($sql, [3]);
```
