### ISSUE TITLE
Numbers being Returned as Strings

### ISSUE THREAD

**Issue by robs007** [zoilomora/laravel-msaccess#5]
It appears that any number fields are being returned as strings, so I can't use sum() in the query. Is there someplace I can add a PDO option to possibly change that?

**Comment by zoilomora** [comment]
Hello, I have not been able to support this library for a long time.
Now I'm back.

I tried to execute the `SELECT SUM (id) FROM Table1` statement and it worked perfectly for me.

Can you teach them the **SQL** and **the structure of the table**?

Is it possible that you are trying to **SUM** a **field of text type**?

**Comment by robs007** [comment]
From what I’m reading maybe just the way pdo works with  access, you may not be able to do anything about it.
Thanks
Here is the Access table
[cid:image001.jpg@01D5253D.926E1BA0]


Here is the query I’m trying to run.
return self::wherebetween('DateOfSummary',[$startDate, $endDate])
->sum('TotalManifests')
->sum('TotalFunJumps')
->sum('TotalJumpMasterJumps')
->sum('TotalTandemJumps')
->sum('TotalBlockJumps')
->sum('TotalVendorJumps')
->sum('TotalStaffJumps')
->sum('TotalManifestValue')
->sum('TotalJumpCharge')
->sum('TotalJumpDiscount')
->sum('TotalJumpTax')
->sum('TotalAdditionalServiceCharge')
->sum('TotalAdditionalServiceDiscount')
->sum('TotalAdditionalServiceTax')
->sum('TotalEquipmentCharge')
->sum('Total EquipmentDiscount')
->sum('TotalEquipmentTax')
->sum('TotalPaymentAmount')
->sum('TotalPaymentSurcharge')
->sum('TotalTransfersIN')
->sum('TotalTransfersOUT')
->sum('TotalCreditsIssued')
->sum('TotalCashAmountIssued')
->sum('TotalStaffPaymentIssued')
->sum('TotalRefundsIssued')
->sum('TotalDebitsIssued')
->sum('TotalRentals')
->sum('TotalMembershipCharges')
->sum('TotalGearstoreSales');

And here’s the error I get

[cid:image005.jpg@01D5253D.926E1BA0]

**Comment by zoilomora** [comment]
@robs007 Try uploading the image directly on github. https://github.com/zoilomora/laravel-msaccess/issues/5

By email they are not published.

**Comment by robs007** [comment]
![Annotation 2019-06-18 060429](https://user-images.githubusercontent.com/947023/59673280-01ea6480-918f-11e9-9503-cd4ff373deec.jpg)

![Annotation 2019-06-18 060242](https://user-images.githubusercontent.com/947023/59673133-bcc63280-918e-11e9-8fe2-bf8ff2eb3609.jpg)

![Annotation 2019-06-18 055639](https://user-images.githubusercontent.com/947023/59672659-e03cad80-918d-11e9-949d-57739c45cf78.jpg)
![Annotation 2019-06-18 055239](https://user-images.githubusercontent.com/947023/59672397-64426580-918d-11e9-8c9b-9a1b10d57bd0.jpg)

**Comment by robs007** [comment]
Looks like the simple solution is to just use the laravel cast method in the model and set them there and sum them after. Would still be nice to be able to do the suming on the DB side, but I guess this is a work around.

**Comment by zoilomora** [comment]
I am currently focusing on separating the DBAL part of the integration with Laravel and testing it as much as possible.

When that part has it ready, it will be easier to obtain a more stable version of this library that will inherit from DBAL.
